name: mainstream2
channels:
  - conda-forge
dependencies:
  - python >= 3.10
  # dev
  - black
  - jupyter
  - ipykernel
  - ipywidgets
  # data
  - sqlalchemy
  - pandas
  - modin-ray
  - nltk
  # hsbm
  - graph-tool
  # umap-hdbscan
  - umap-learn
  - hdbscan
  # umap.plot
  # - datashader
  # - bokeh
  # - holoviews >= 1.15
  # - scikit-image 
  # - colorcet 
  # analysis
  - seaborn
  # - pingouin
  - scikit-learn
  # polars
  # - polars
  # - pyarrow
  # - connectorx
