name: mainstream
channels:
  - conda-forge
dependencies:
  - python
  # dev
  - black
  - jupyter
  - ipykernel
  - ipywidgets
  # data
  - sqlalchemy
  - pandas
  - nltk
  # hsbm
  - graph-tool
  # umap-hdbscan
  - umap-learn
  - hdbscan
  # analysis
  - seaborn
  # - pingouin
  - scikit-learn
