name: mainstream
channels:
  - conda-forge
dependencies:
  - python >= 3.10
  # dev
  - black
  - jupyter
  - ipykernel
  - ipywidgets
  # data
  - sqlalchemy
  - pandas
  - modin-ray
  - nltk
  # hsbm
  - graph-tool
  # analysis
  - seaborn
  - pingouin
  - scikit-learn
  # metadata
  - python-dotenv
  - pip:
    - pybliometrics