name: mainstream
channels:
  - conda-forge
dependencies:
  - python
  # dev
  - black
  - jupyter
  - ipykernel
  - ipywidgets
  # data
  - sqlalchemy
  - graph-tool
  - pandas
  # analysis
  - seaborn
  # - pingouin
  - scikit-learn
