name: mainstream
channels:
  - conda-forge
dependencies:
  - python
  - pypy
  # dev
  # - black
  # - jupyter
  # - ipykernel
  # - ipywidgets
  # data
  - sqlalchemy
  - graph-tool
  # analysis
  # - seaborn
  # - pingouin

