name: mainstream
channels:
  - conda-forge
dependencies:
  # - pypy
  - black
  - ipykernel
  - ipywidgets
  - tqdm
  # tag
  - nltk
  # data
  - sqlalchemy
  - modin-omnisci
  - seaborn
  #- graph-tool
  #- pingouin

